In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading in Data
df = pd.read_csv('2017_county_health_dataset.csv')
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2017,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,2017,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,2017,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,2017,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,2017,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...,...
57,2017,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,2017,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,2017,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,2017,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,2017,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [3]:
# Selecting the columns we only want
select_df = df[['FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [4]:
# Removing the first row that was NaN 
select_df = select_df.dropna(how='all')
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [5]:

select_df.head(60)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
5,36011,Cayuga,849,12,6,8.3,32,4679,0.001546
6,36013,Chautauqua,1655,15,8,7.8,66,8193,0.001323
7,36015,Chemung,1111,14,8,7.6,45,4457,0.002421
8,36017,Chenango,660,14,7,8.4,35,3388,0.001821
9,36019,Clinton,896,14,7,7.5,34,5074,0.001957
10,36021,Columbia,777,12,8,8.3,29,4268,0.001495
11,36023,Cortland,572,13,7,8.1,27,2854,0.002725
12,36025,Delaware,656,15,8,8.4,42,3345,0.001064
13,36027,Dutchess,2870,12,7,8.3,121,19181,0.002415
14,36029,Erie,10919,14,8,7.5,255,51633,0.002278
15,36031,Essex,506,12,8,8.3,28,2514,0.001403
16,36033,Franklin,558,15,8,7.4,30,4086,0.002410
17,36035,Fulton,749,15,8,7.8,28,3945,0.001018
18,36037,Genesee,648,12,6,8.5,40,3821,0.001290
19,36039,Greene,663,13,9,8.1,35,3156,0.000714
20,36041,Hamilton,101,12,6,8.1,4,334,0.000424
21,36043,Herkimer,773,14,7,7.8,33,4234,0.000444
22,36045,Jefferson,1162,15,7,7.4,67,8096,0.001555
23,36047,Kings,21743,17,8,6.8,389,282455,0.001745
24,36049,Lewis,292,12,6,7.8,23,2117,0.002151
25,36051,Livingston,588,13,6,7.7,31,3393,0.000773
26,36053,Madison,771,12,6,8.2,35,4055,0.001490
27,36055,Monroe,7140,13,8,7.4,194,42806,0.002101
28,36057,Montgomery,619,17,7,6.4,27,3389,0.000806
29,36059,Nassau,10514,11,8,9.6,439,80572,0.002639
30,36061,New York,11893,15,9,7.8,202,120131,0.007299
31,36063,Niagara,2850,14,8,7.7,93,12454,0.000992
32,36065,Oneida,2743,15,8,7.7,75,14281,0.001351
33,36067,Onondaga,4771,14,8,7.6,143,27481,0.002020
34,36069,Ontario,1173,12,7,8.5,79,6352,0.001733
35,36071,Orange,3316,14,7,8.5,174,26102,0.001919
36,36073,Orleans,564,14,7,7.7,20,3076,0.000457
37,36075,Oswego,1523,15,7,7.9,98,8134,0.001115
38,36077,Otsego,700,15,6,7.5,22,4084,0.001698
39,36079,Putnam,841,11,8,9.2,41,6069,0.002725
40,36081,Queens,17289,17,8,8.2,411,315982,0.001325
41,36083,Rensselaer,1842,12,7,7.9,50,8705,0.001416
42,36085,Richmond,4704,14,8,8.7,83,31670,0.001923
43,36087,Rockland,2237,15,6,8.5,81,24101,0.002358
44,36089,St. Lawrence,1305,14,7,7.4,54,7469,0.001667
45,36091,Saratoga,1979,10,7,8.7,86,10089,0.001397
46,36093,Schenectady,1706,12,8,7.5,36,9939,0.001894
47,36095,Schoharie,355,12,7,8.3,12,2038,0.000926
48,36097,Schuyler,223,13,7,8.4,10,1095,0.001484
49,36099,Seneca,432,14,6,8.4,31,2369,0.001608
50,36101,Steuben,1210,14,7,7.8,49,6578,0.001567
51,36103,Suffolk,13618,11,8,9.2,721,109506,0.002326
52,36105,Sullivan,1115,15,9,7.6,66,6580,0.001736
53,36107,Tioga,552,12,7,8.6,26,2753,0.001314
54,36109,Tompkins,788,13,7,7.5,50,6391,0.002985
55,36111,Ulster,1967,12,7,8.1,77,13094,0.003040
56,36113,Warren,785,12,7,8.1,29,3777,0.003215
57,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,36119,Westchester,7086,14,8,9.0,192,81967,0.003322

In [6]:
# Removing the row that was NaN 
select_df = select_df.drop(labels=21, axis=0)
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [7]:
# Removing the row that was NaN
# Also drop First Row (NY State)
select_df = select_df.drop(labels=62, axis=0)
select_df = select_df.drop(labels=0, axis=0)

select_df

KeyError: '[62] not found in axis'

In [8]:
select_df.head(22)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
5,36011,Cayuga,849,12,6,8.3,32,4679,0.001546
6,36013,Chautauqua,1655,15,8,7.8,66,8193,0.001323
7,36015,Chemung,1111,14,8,7.6,45,4457,0.002421
8,36017,Chenango,660,14,7,8.4,35,3388,0.001821
9,36019,Clinton,896,14,7,7.5,34,5074,0.001957
10,36021,Columbia,777,12,8,8.3,29,4268,0.001495
11,36023,Cortland,572,13,7,8.1,27,2854,0.002725
12,36025,Delaware,656,15,8,8.4,42,3345,0.001064
13,36027,Dutchess,2870,12,7,8.3,121,19181,0.002415
14,36029,Erie,10919,14,8,7.5,255,51633,0.002278
15,36031,Essex,506,12,8,8.3,28,2514,0.001403
16,36033,Franklin,558,15,8,7.4,30,4086,0.002410
17,36035,Fulton,749,15,8,7.8,28,3945,0.001018
18,36037,Genesee,648,12,6,8.5,40,3821,0.001290
19,36039,Greene,663,13,9,8.1,35,3156,0.000714
20,36041,Hamilton,101,12,6,8.1,4,334,0.000424
22,36045,Jefferson,1162,15,7,7.4,67,8096,0.001555

In [9]:
# The the year for the dataset
#select_df["Years"] = "2017"
select_df["Years"] = 2017

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio,Years
0,36001,Albany,2996,12,9,7.7,97,18101,0.003021,2017
1,36003,Allegany,539,14,7,8.1,18,3028,0.001748,2017
2,36005,Bronx,14187,28,10,7.1,243,173351,0.001647,2017
3,36007,Broome,2312,14,8,7.6,68,11189,0.001825,2017
4,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976,2017
...,...,...,...,...,...,...,...,...,...,...
57,36115,Washington,722,13,8,8.2,46,4281,0.001157,2017
58,36117,Wayne,1016,12,7,8.4,53,5989,0.000798,2017
59,36119,Westchester,7086,14,8,9.0,192,81967,0.003322,2017
60,36121,Wyoming,463,13,6,8.1,23,2263,0.001634,2017
61,36123,Yates,282,13,5,8.6,22,2449,0.000918,2017

In [10]:
# Reorganizing the dataset
clean_data = select_df[['Years', 'FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2017,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,2017,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,2017,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,2017,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,2017,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...,...
57,2017,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,2017,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,2017,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,2017,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,2017,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [14]:
#Drop row 50 (NaN)

# Removing the row that was NaN
# Also drop First Row (NY State)
clean_data = clean_data.drop(labels=50, axis=0)
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2016,36001.0,Albany,3013.0,12.0,9.0,7.7,91.0,21914.0,0.002882
1,2016,36003.0,Allegany,539.0,14.0,7.0,7.9,21.0,3968.0,0.001698
2,2016,36005.0,Bronx,14174.0,29.0,10.0,7.0,253.0,191922.0,0.001493
3,2016,36007.0,Broome,2298.0,14.0,8.0,7.5,66.0,15312.0,0.001754
4,2016,36009.0,Cattaraugus,1035.0,14.0,7.0,7.9,51.0,7397.0,0.000929
5,2016,36011.0,Cayuga,854.0,12.0,7.0,8.2,32.0,6503.0,0.001420
6,2016,36013.0,Chautauqua,1643.0,14.0,8.0,7.7,66.0,11224.0,0.001203
7,2016,36015.0,Chemung,1076.0,13.0,8.0,7.4,42.0,5948.0,0.002155
8,2016,36017.0,Chenango,639.0,13.0,7.0,8.3,38.0,3961.0,0.001681
9,2016,36019.0,Clinton,883.0,13.0,7.0,7.3,41.0,6397.0,0.001789
10,2016,36021.0,Columbia,765.0,12.0,7.0,8.2,32.0,5318.0,0.001319
11,2016,36023.0,Cortland,569.0,12.0,7.0,7.9,23.0,3461.0,0.002506
12,2016,36025.0,Delaware,670.0,12.0,7.0,8.3,43.0,4240.0,0.001009
13,2016,36027.0,Dutchess,2850.0,13.0,7.0,8.2,108.0,22181.0,0.002273
14,2016,36029.0,Erie,10724.0,14.0,8.0,7.5,263.0,62930.0,0.002128
15,2016,36031.0,Essex,472.0,12.0,9.0,8.1,30.0,3192.0,0.001344
16,2016,36033.0,Franklin,585.0,15.0,8.0,7.3,33.0,4941.0,0.002320
17,2016,36035.0,Fulton,730.0,13.0,8.0,7.7,31.0,4622.0,0.000924
18,2016,36037.0,Genesee,677.0,12.0,6.0,8.3,43.0,4826.0,0.001285
19,2016,36039.0,Greene,661.0,12.0,9.0,7.9,39.0,3811.0,0.000709
20,2016,36041.0,Hamilton,93.0,10.0,5.0,8.1,4.0,460.0,0.000212
22,2016,36045.0,Jefferson,1171.0,13.0,7.0,7.2,63.0,10236.0,0.001395
23,2016,36047.0,Kings,22003.0,20.0,8.0,6.8,399.0,336464.0,0.001637
24,2016,36049.0,Lewis,274.0,12.0,7.0,7.7,23.0,2737.0,0.002020
25,2016,36051.0,Livingston,622.0,13.0,6.0,7.6,39.0,4496.0,0.000712
26,2016,36053.0,Madison,701.0,12.0,6.0,8.0,36.0,4934.0,0.001381
27,2016,36055.0,Monroe,7011.0,13.0,8.0,7.4,211.0,57795.0,0.001996
28,2016,36057.0,Montgomery,595.0,15.0,7.0,6.2,25.0,4713.0,0.000824
29,2016,36059.0,Nassau,10372.0,12.0,8.0,9.5,451.0,115073.0,0.002558
30,2016,36061.0,New York,12134.0,14.0,9.0,7.8,219.0,146866.0,0.006944
31,2016,36063.0,Niagara,2757.0,13.0,8.0,7.6,93.0,17892.0,0.000960
32,2016,36065.0,Oneida,2673.0,13.0,8.0,7.6,90.0,18491.0,0.001309
33,2016,36067.0,Onondaga,4648.0,13.0,8.0,7.6,150.0,40503.0,0.001919
34,2016,36069.0,Ontario,1157.0,11.0,7.0,8.4,70.0,7719.0,0.001631
35,2016,36071.0,Orange,3311.0,14.0,7.0,8.4,188.0,33616.0,0.001828
36,2016,36073.0,Orleans,532.0,14.0,7.0,7.7,23.0,3697.0,0.000429
37,2016,36075.0,Oswego,1416.0,14.0,7.0,7.8,92.0,10157.0,0.001042
38,2016,36077.0,Otsego,671.0,13.0,6.0,7.4,21.0,5628.0,0.001603
39,2016,36079.0,Putnam,845.0,10.0,8.0,9.1,36.0,7566.0,0.002632
40,2016,36081.0,Queens,17036.0,18.0,8.0,8.2,403.0,380815.0,0.001259
41,2016,36083.0,Rensselaer,1776.0,12.0,7.0,7.8,63.0,11082.0,0.001408
42,2016,36085.0,Richmond,4617.0,13.0,8.0,8.7,82.0,40931.0,0.001835
43,2016,36087.0,Rockland,2273.0,13.0,6.0,8.5,86.0,30357.0,0.002283
44,2016,36089.0,St. Lawrence,1295.0,14.0,7.0,7.2,54.0,10229.0,0.001464
45,2016,36091.0,Saratoga,1955.0,10.0,7.0,8.6,85.0,13478.0,0.001330
46,2016,36093.0,Schenectady,1642.0,12.0,9.0,7.4,31.0,12313.0,0.001818
47,2016,36095.0,Schoharie,337.0,12.0,7.0,8.2,14.0,2662.0,0.000919
48,2016,36097.0,Schuyler,229.0,12.0,6.0,8.4,8.0,1585.0,0.001462
49,2016,36099.0,Seneca,399.0,13.0,6.0,8.3,29.0,2767.0,0.001490
51,2016,36103.0,Suffolk,13411.0,12.0,8.0,9.1,691.0,134882.0,0.002217
52,2016,36105.0,Sullivan,1120.0,15.0,9.0,7.5,62.0,8973.0,0.001304
53,2016,36107.0,Tioga,538.0,11.0,7.0,8.4,29.0,3864.0,0.001244
54,2016,36109.0,Tompkins,778.0,13.0,7.0,7.5,49.0,9151.0,0.002849
55,2016,36111.0,Ulster,1977.0,13.0,7.0,7.9,83.0,18032.0,0.002967
56,2016,36113.0,Warren,747.0,11.0,7.0,8.1,33.0,5244.0,0.002924
57,2016,36115.0,Washington,743.0,12.0,8.0,8.1,47.0,5403.0,0.001091
58,2016,36117.0,Wayne,1019.0,12.0,7.0,8.3,48.0,7779.0,0.000793
59,2016,36119.0,Westchester,7013.0,13.0,8.0,8.9,183.0,94774.0,0.003185
60,2016,36121.0,Wyoming,447.0,12.0,6.0,8.0,22.0,3018.0,0.001481
61,2016,36123.0,Yates,267.0,13.0,5.0,8.5,23.0,2703.0,0.000833

In [11]:
clean_data.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                            int64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [12]:
# Spliting the Mental Health Provider Ratio 
changing = clean_data['Mental Health Provider Ratio'].str.split(':', expand=True)
changing.dtypes

AttributeError: Can only use .str accessor with string values!

In [13]:
# Converting the string into int
changing = changing.astype('int')

NameError: name 'changing' is not defined

In [20]:
# Changing the Mental Health Provider Ratio into a int value
clean_data['Mental Health Provider Ratio'] = changing[1]/changing[0]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2011,36001.0,Albany,2948.0,12.0,8.0,0.0,0.0,0.0,0.002985
2,2011,36003.0,Allegany,565.0,16.0,6.7,0.0,0.0,0.0,0.000243
3,2011,36005.0,Bronx,14630.0,26.0,9.7,0.0,0.0,0.0,0.000957
4,2011,36007.0,Broome,2243.0,13.0,7.6,0.0,0.0,0.0,0.000262
5,2011,36009.0,Cattaraugus,1007.0,20.0,6.9,0.0,0.0,0.0,0.000075
6,2011,36011.0,Cayuga,842.0,15.0,7.3,0.0,0.0,0.0,0.000201
7,2011,36013.0,Chautauqua,1494.0,17.0,7.4,0.0,0.0,0.0,0.002075
8,2011,36015.0,Chemung,1005.0,21.0,8.5,0.0,0.0,0.0,0.002137
9,2011,36017.0,Chenango,602.0,13.0,6.9,0.0,0.0,0.0,0.002941
10,2011,36019.0,Clinton,845.0,16.0,7.8,0.0,0.0,0.0,0.000343
11,2011,36021.0,Columbia,738.0,13.0,7.0,0.0,0.0,0.0,0.000097
12,2011,36023.0,Cortland,510.0,18.0,8.0,0.0,0.0,0.0,0.001767
13,2011,36025.0,Delaware,638.0,13.0,6.9,0.0,0.0,0.0,0.000131
14,2011,36027.0,Dutchess,2652.0,10.0,6.9,0.0,0.0,0.0,0.002433
15,2011,36029.0,Erie,10681.0,14.0,8.3,0.0,0.0,0.0,0.000170
16,2011,36031.0,Essex,425.0,11.0,5.9,0.0,0.0,0.0,0.004310
17,2011,36033.0,Franklin,559.0,16.0,8.1,0.0,0.0,0.0,0.000139
18,2011,36035.0,Fulton,618.0,19.0,7.0,0.0,0.0,0.0,0.000544
19,2011,36037.0,Genesee,595.0,14.0,6.0,0.0,0.0,0.0,0.000242
20,2011,36039.0,Greene,671.0,13.0,8.4,0.0,0.0,0.0,0.000326
22,2011,36043.0,Herkimer,722.0,14.0,6.6,0.0,0.0,0.0,0.000048
23,2011,36045.0,Jefferson,1088.0,13.0,6.7,0.0,0.0,0.0,0.000060
24,2011,36047.0,Kings,23756.0,22.0,8.6,0.0,0.0,0.0,0.000167
25,2011,36049.0,Lewis,282.0,16.0,6.5,0.0,0.0,0.0,0.000115
26,2011,36051.0,Livingston,576.0,12.0,5.8,0.0,0.0,0.0,0.000032
27,2011,36053.0,Madison,683.0,13.0,7.3,0.0,0.0,0.0,0.000285
28,2011,36055.0,Monroe,6698.0,16.0,7.8,0.0,0.0,0.0,0.000485
29,2011,36057.0,Montgomery,569.0,12.0,7.1,0.0,0.0,0.0,0.000494
30,2011,36059.0,Nassau,10280.0,13.0,7.7,0.0,0.0,0.0,0.000429
31,2011,36061.0,New York,13616.0,19.0,8.4,0.0,0.0,0.0,0.001287
32,2011,36063.0,Niagara,2627.0,15.0,7.7,0.0,0.0,0.0,0.000061
33,2011,36065.0,Oneida,2600.0,14.0,8.4,0.0,0.0,0.0,0.000195
34,2011,36067.0,Onondaga,4518.0,14.0,8.2,0.0,0.0,0.0,0.000329
35,2011,36069.0,Ontario,1008.0,9.0,6.2,0.0,0.0,0.0,0.000324
36,2011,36071.0,Orange,3264.0,17.0,6.8,0.0,0.0,0.0,0.000883
37,2011,36073.0,Orleans,418.0,17.0,7.3,0.0,0.0,0.0,0.026316
38,2011,36075.0,Oswego,1376.0,18.0,7.5,0.0,0.0,0.0,0.000074
39,2011,36077.0,Otsego,622.0,12.0,7.6,0.0,0.0,0.0,0.000760
40,2011,36079.0,Putnam,770.0,9.0,6.9,0.0,0.0,0.0,0.000293
41,2011,36081.0,Queens,17881.0,20.0,8.2,0.0,0.0,0.0,0.000174
42,2011,36083.0,Rensselaer,1615.0,14.0,7.4,0.0,0.0,0.0,0.000071
43,2011,36085.0,Richmond,4449.0,15.0,7.9,0.0,0.0,0.0,0.000197
44,2011,36087.0,Rockland,2224.0,16.0,6.7,0.0,0.0,0.0,0.000472
45,2011,36089.0,St. Lawrence,1300.0,16.0,7.4,0.0,0.0,0.0,0.000703
46,2011,36091.0,Saratoga,1820.0,11.0,6.2,0.0,0.0,0.0,0.000257
47,2011,36093.0,Schenectady,1509.0,12.0,8.1,0.0,0.0,0.0,0.000152
48,2011,36095.0,Schoharie,324.0,14.0,6.4,0.0,0.0,0.0,0.009434
49,2011,36097.0,Schuyler,195.0,14.0,6.2,0.0,0.0,0.0,0.001114
51,2011,36101.0,Steuben,1164.0,14.0,7.6,0.0,0.0,0.0,0.000062
52,2011,36103.0,Suffolk,13094.0,13.0,7.4,0.0,0.0,0.0,0.000195
53,2011,36105.0,Sullivan,1019.0,16.0,7.9,0.0,0.0,0.0,0.000184
54,2011,36107.0,Tioga,554.0,11.0,7.9,0.0,0.0,0.0,0.000060
55,2011,36109.0,Tompkins,647.0,13.0,6.7,0.0,0.0,0.0,0.000376
56,2011,36111.0,Ulster,1930.0,12.0,7.3,0.0,0.0,0.0,0.000721
57,2011,36113.0,Warren,742.0,11.0,6.6,0.0,0.0,0.0,0.001456
58,2011,36115.0,Washington,670.0,18.0,7.4,0.0,0.0,0.0,0.006944
59,2011,36117.0,Wayne,991.0,14.0,6.5,0.0,0.0,0.0,0.000055
60,2011,36119.0,Westchester,7144.0,12.0,7.9,0.0,0.0,0.0,0.003759
61,2011,36121.0,Wyoming,405.0,13.0,5.1,0.0,0.0,0.0,0.001325

In [14]:
clean_data.shape

(61, 10)

In [22]:
clean_data.head(60)

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2011,36001.0,Albany,2948.0,12.0,8.0,0.0,0.0,0.0,0.002985
2,2011,36003.0,Allegany,565.0,16.0,6.7,0.0,0.0,0.0,0.000243
3,2011,36005.0,Bronx,14630.0,26.0,9.7,0.0,0.0,0.0,0.000957
4,2011,36007.0,Broome,2243.0,13.0,7.6,0.0,0.0,0.0,0.000262
5,2011,36009.0,Cattaraugus,1007.0,20.0,6.9,0.0,0.0,0.0,0.000075
6,2011,36011.0,Cayuga,842.0,15.0,7.3,0.0,0.0,0.0,0.000201
7,2011,36013.0,Chautauqua,1494.0,17.0,7.4,0.0,0.0,0.0,0.002075
8,2011,36015.0,Chemung,1005.0,21.0,8.5,0.0,0.0,0.0,0.002137
9,2011,36017.0,Chenango,602.0,13.0,6.9,0.0,0.0,0.0,0.002941
10,2011,36019.0,Clinton,845.0,16.0,7.8,0.0,0.0,0.0,0.000343
11,2011,36021.0,Columbia,738.0,13.0,7.0,0.0,0.0,0.0,0.000097
12,2011,36023.0,Cortland,510.0,18.0,8.0,0.0,0.0,0.0,0.001767
13,2011,36025.0,Delaware,638.0,13.0,6.9,0.0,0.0,0.0,0.000131
14,2011,36027.0,Dutchess,2652.0,10.0,6.9,0.0,0.0,0.0,0.002433
15,2011,36029.0,Erie,10681.0,14.0,8.3,0.0,0.0,0.0,0.000170
16,2011,36031.0,Essex,425.0,11.0,5.9,0.0,0.0,0.0,0.004310
17,2011,36033.0,Franklin,559.0,16.0,8.1,0.0,0.0,0.0,0.000139
18,2011,36035.0,Fulton,618.0,19.0,7.0,0.0,0.0,0.0,0.000544
19,2011,36037.0,Genesee,595.0,14.0,6.0,0.0,0.0,0.0,0.000242
20,2011,36039.0,Greene,671.0,13.0,8.4,0.0,0.0,0.0,0.000326
22,2011,36043.0,Herkimer,722.0,14.0,6.6,0.0,0.0,0.0,0.000048
23,2011,36045.0,Jefferson,1088.0,13.0,6.7,0.0,0.0,0.0,0.000060
24,2011,36047.0,Kings,23756.0,22.0,8.6,0.0,0.0,0.0,0.000167
25,2011,36049.0,Lewis,282.0,16.0,6.5,0.0,0.0,0.0,0.000115
26,2011,36051.0,Livingston,576.0,12.0,5.8,0.0,0.0,0.0,0.000032
27,2011,36053.0,Madison,683.0,13.0,7.3,0.0,0.0,0.0,0.000285
28,2011,36055.0,Monroe,6698.0,16.0,7.8,0.0,0.0,0.0,0.000485
29,2011,36057.0,Montgomery,569.0,12.0,7.1,0.0,0.0,0.0,0.000494
30,2011,36059.0,Nassau,10280.0,13.0,7.7,0.0,0.0,0.0,0.000429
31,2011,36061.0,New York,13616.0,19.0,8.4,0.0,0.0,0.0,0.001287
32,2011,36063.0,Niagara,2627.0,15.0,7.7,0.0,0.0,0.0,0.000061
33,2011,36065.0,Oneida,2600.0,14.0,8.4,0.0,0.0,0.0,0.000195
34,2011,36067.0,Onondaga,4518.0,14.0,8.2,0.0,0.0,0.0,0.000329
35,2011,36069.0,Ontario,1008.0,9.0,6.2,0.0,0.0,0.0,0.000324
36,2011,36071.0,Orange,3264.0,17.0,6.8,0.0,0.0,0.0,0.000883
37,2011,36073.0,Orleans,418.0,17.0,7.3,0.0,0.0,0.0,0.026316
38,2011,36075.0,Oswego,1376.0,18.0,7.5,0.0,0.0,0.0,0.000074
39,2011,36077.0,Otsego,622.0,12.0,7.6,0.0,0.0,0.0,0.000760
40,2011,36079.0,Putnam,770.0,9.0,6.9,0.0,0.0,0.0,0.000293
41,2011,36081.0,Queens,17881.0,20.0,8.2,0.0,0.0,0.0,0.000174
42,2011,36083.0,Rensselaer,1615.0,14.0,7.4,0.0,0.0,0.0,0.000071
43,2011,36085.0,Richmond,4449.0,15.0,7.9,0.0,0.0,0.0,0.000197
44,2011,36087.0,Rockland,2224.0,16.0,6.7,0.0,0.0,0.0,0.000472
45,2011,36089.0,St. Lawrence,1300.0,16.0,7.4,0.0,0.0,0.0,0.000703
46,2011,36091.0,Saratoga,1820.0,11.0,6.2,0.0,0.0,0.0,0.000257
47,2011,36093.0,Schenectady,1509.0,12.0,8.1,0.0,0.0,0.0,0.000152
48,2011,36095.0,Schoharie,324.0,14.0,6.4,0.0,0.0,0.0,0.009434
49,2011,36097.0,Schuyler,195.0,14.0,6.2,0.0,0.0,0.0,0.001114
51,2011,36101.0,Steuben,1164.0,14.0,7.6,0.0,0.0,0.0,0.000062
52,2011,36103.0,Suffolk,13094.0,13.0,7.4,0.0,0.0,0.0,0.000195
53,2011,36105.0,Sullivan,1019.0,16.0,7.9,0.0,0.0,0.0,0.000184
54,2011,36107.0,Tioga,554.0,11.0,7.9,0.0,0.0,0.0,0.000060
55,2011,36109.0,Tompkins,647.0,13.0,6.7,0.0,0.0,0.0,0.000376
56,2011,36111.0,Ulster,1930.0,12.0,7.3,0.0,0.0,0.0,0.000721
57,2011,36113.0,Warren,742.0,11.0,6.6,0.0,0.0,0.0,0.001456
58,2011,36115.0,Washington,670.0,18.0,7.4,0.0,0.0,0.0,0.006944
59,2011,36117.0,Wayne,991.0,14.0,6.5,0.0,0.0,0.0,0.000055
60,2011,36119.0,Westchester,7144.0,12.0,7.9,0.0,0.0,0.0,0.003759
61,2011,36121.0,Wyoming,405.0,13.0,5.1,0.0,0.0,0.0,0.001325

In [15]:
#convert all objects to integer
df = pd.DataFrame(clean_data)
df = df.astype({"FIPS":"int",
                        "Years":"object",
                        "Deaths":"int",
                        "% Fair or Poor Health":"int",
                        "% Low birthweight":"int",
                        "# Driving Deaths":"int",
                        "# Uninsured":"int"})

In [16]:

df.dtypes

Years                            object
FIPS                              int32
County                           object
Deaths                            int32
% Fair or Poor Health             int32
% Low birthweight                 int32
Food Environment Index          float64
# Driving Deaths                  int32
# Uninsured                       int32
Mental Health Provider Ratio    float64
dtype: object

In [17]:
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2017,36001,Albany,2996,12,9,7.7,97,18101,0.003021
1,2017,36003,Allegany,539,14,7,8.1,18,3028,0.001748
2,2017,36005,Bronx,14187,28,10,7.1,243,173351,0.001647
3,2017,36007,Broome,2312,14,8,7.6,68,11189,0.001825
4,2017,36009,Cattaraugus,1015,15,8,8.0,40,6023,0.000976
...,...,...,...,...,...,...,...,...,...,...
57,2017,36115,Washington,722,13,8,8.2,46,4281,0.001157
58,2017,36117,Wayne,1016,12,7,8.4,53,5989,0.000798
59,2017,36119,Westchester,7086,14,8,9.0,192,81967,0.003322
60,2017,36121,Wyoming,463,13,6,8.1,23,2263,0.001634
61,2017,36123,Yates,282,13,5,8.6,22,2449,0.000918

In [18]:
# Saving the new and cleaned dataset
file_path = "2017_clean_dataset.csv"
clean_data.to_csv(file_path, index=False)