In [2]:
import pandas as pd
import numpy as np

In [3]:
# Reading in Data
df = pd.read_csv('2019_county_health_dataset.csv')
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2019,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,2019,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,2019,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,2019,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,2019,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
...,...,...,...,...,...,...,...,...,...,...
57,2019,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,2019,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,2019,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,2019,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,2019,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [4]:
# Selecting the columns we only want
select_df = df[['FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [5]:
# Removing the first row that was NaN 
select_df = select_df.dropna(how='all')
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [6]:

select_df.head(60)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
5,36011,Cayuga,955,14,6,8.7,38,3361,0.001701
6,36013,Chautauqua,1889,18,7,7.9,53,5619,0.001488
7,36015,Chemung,1256,16,7,7.9,31,3076,0.002755
8,36017,Chenango,734,16,7,8.6,30,1985,0.001923
9,36019,Clinton,898,15,7,7.6,30,3798,0.002309
10,36021,Columbia,846,12,6,8.5,42,2991,0.001667
11,36023,Cortland,608,16,7,8.3,30,1702,0.003185
12,36025,Delaware,655,15,7,8.6,32,2160,0.001156
13,36027,Dutchess,2986,13,8,8.6,117,12198,0.002653
14,36029,Erie,11652,16,9,7.9,241,33803,0.002778
15,36031,Essex,513,13,7,8.8,17,1491,0.001397
16,36033,Franklin,631,15,8,7.6,19,2434,0.002584
17,36035,Fulton,785,17,7,8.2,24,2528,0.001597
18,36037,Genesee,722,17,6,8.8,39,2472,0.001536
19,36039,Greene,681,16,8,8.3,38,2001,0.000822
20,36041,Hamilton,75,12,5,7.8,3,217,0.000446
21,36043,Herkimer,825,14,7,8.1,35,2585,0.000450
22,36045,Jefferson,1199,17,7,7.8,45,5656,0.001805
23,36047,Kings,21908,18,8,7.4,343,198931,0.001980
24,36049,Lewis,307,13,7,8.1,22,1307,0.002110
25,36051,Livingston,659,14,6,8.3,26,2210,0.000972
26,36053,Madison,759,13,6,8.8,33,2682,0.001776
27,36055,Monroe,7677,15,8,7.9,203,29587,0.002500
28,36057,Montgomery,669,16,7,7.8,25,2372,0.000792
29,36059,Nassau,10768,12,8,9.7,417,56454,0.002841
30,36061,New York,11857,15,8,8.3,198,85635,0.007874
31,36063,Niagara,3022,16,8,8.2,95,8540,0.001046
32,36065,Oneida,3000,16,8,8.1,88,8892,0.001527
33,36067,Onondaga,5174,14,8,8.1,149,19703,0.002299
34,36069,Ontario,1287,13,7,8.6,60,3911,0.002037
35,36071,Orange,3602,16,7,8.8,166,19544,0.002212
36,36073,Orleans,533,18,7,8.1,26,2053,0.000537
37,36075,Oswego,1572,16,7,8.1,94,5083,0.001292
38,36077,Otsego,729,15,7,7.9,26,2670,0.001912
39,36079,Putnam,943,11,8,9.4,32,3959,0.002967
40,36081,Queens,17755,18,8,8.8,383,225096,0.001471
41,36083,Rensselaer,1849,14,8,8.3,47,6332,0.001546
42,36085,Richmond,4902,18,8,9.1,83,21728,0.002101
43,36087,Rockland,2372,14,6,8.8,78,17759,0.002500
44,36089,St. Lawrence,1350,17,7,7.7,56,5360,0.001825
45,36091,Saratoga,2265,11,7,8.9,84,8005,0.001563
46,36093,Schenectady,1852,14,8,8.3,36,6130,0.002083
47,36095,Schoharie,395,14,7,8.1,12,1353,0.001209
48,36097,Schuyler,274,17,7,8.4,12,804,0.001610
49,36099,Seneca,465,15,6,8.3,26,1649,0.001709
50,36101,Steuben,1274,16,7,8.3,44,4594,0.001712
51,36103,Suffolk,14659,14,8,9.4,696,74327,0.002532
52,36105,Sullivan,1106,19,9,8.3,55,4087,0.001894
53,36107,Tioga,578,15,7,8.8,19,1869,0.001420
54,36109,Tompkins,883,15,6,7.8,47,4429,0.003390
55,36111,Ulster,2216,14,7,8.2,89,9049,0.003236
56,36113,Warren,889,11,7,8.5,25,2623,0.003663
57,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,36119,Westchester,7174,14,8,9.2,199,61342,0.003636

In [7]:
# Removing the row that was NaN 
select_df = select_df.drop(labels=21, axis=0)
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [8]:
# Removing the row that was NaN
# Also drop First Row (NY State)
select_df = select_df.drop(labels=62, axis=0)
select_df = select_df.drop(labels=0, axis=0)

select_df

KeyError: '[62] not found in axis'

In [9]:
select_df.head(22)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
5,36011,Cayuga,955,14,6,8.7,38,3361,0.001701
6,36013,Chautauqua,1889,18,7,7.9,53,5619,0.001488
7,36015,Chemung,1256,16,7,7.9,31,3076,0.002755
8,36017,Chenango,734,16,7,8.6,30,1985,0.001923
9,36019,Clinton,898,15,7,7.6,30,3798,0.002309
10,36021,Columbia,846,12,6,8.5,42,2991,0.001667
11,36023,Cortland,608,16,7,8.3,30,1702,0.003185
12,36025,Delaware,655,15,7,8.6,32,2160,0.001156
13,36027,Dutchess,2986,13,8,8.6,117,12198,0.002653
14,36029,Erie,11652,16,9,7.9,241,33803,0.002778
15,36031,Essex,513,13,7,8.8,17,1491,0.001397
16,36033,Franklin,631,15,8,7.6,19,2434,0.002584
17,36035,Fulton,785,17,7,8.2,24,2528,0.001597
18,36037,Genesee,722,17,6,8.8,39,2472,0.001536
19,36039,Greene,681,16,8,8.3,38,2001,0.000822
20,36041,Hamilton,75,12,5,7.8,3,217,0.000446
22,36045,Jefferson,1199,17,7,7.8,45,5656,0.001805

In [10]:
# The the year for the dataset
#select_df["Years"] = "2019"
select_df["Years"] = 2019

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio,Years
0,36001,Albany,3202,13,8,8.1,100,10741,0.003344,2019
1,36003,Allegany,596,15,7,8.2,18,1936,0.001919,2019
2,36005,Bronx,14817,27,9,7.8,216,116497,0.001866,2019
3,36007,Broome,2442,17,8,8.1,66,8158,0.001927,2019
4,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112,2019
...,...,...,...,...,...,...,...,...,...,...
57,36115,Washington,796,14,7,8.4,37,2636,0.001362,2019
58,36117,Wayne,1197,16,7,8.6,54,3992,0.000937,2019
59,36119,Westchester,7174,14,8,9.2,199,61342,0.003636,2019
60,36121,Wyoming,509,16,6,8.3,22,1632,0.002000,2019
61,36123,Yates,281,13,5,8.9,10,1816,0.001082,2019

In [11]:
# Reorganizing the dataset
clean_data = select_df[['Years', 'FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2019,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,2019,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,2019,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,2019,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,2019,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
...,...,...,...,...,...,...,...,...,...,...
57,2019,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,2019,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,2019,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,2019,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,2019,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [12]:
#Drop row 50 (NaN)

# Removing the row that was NaN
# Also drop First Row (NY State)
clean_data = clean_data.drop(labels=50, axis=0)
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2019,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,2019,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,2019,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,2019,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,2019,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
5,2019,36011,Cayuga,955,14,6,8.7,38,3361,0.001701
6,2019,36013,Chautauqua,1889,18,7,7.9,53,5619,0.001488
7,2019,36015,Chemung,1256,16,7,7.9,31,3076,0.002755
8,2019,36017,Chenango,734,16,7,8.6,30,1985,0.001923
9,2019,36019,Clinton,898,15,7,7.6,30,3798,0.002309
10,2019,36021,Columbia,846,12,6,8.5,42,2991,0.001667
11,2019,36023,Cortland,608,16,7,8.3,30,1702,0.003185
12,2019,36025,Delaware,655,15,7,8.6,32,2160,0.001156
13,2019,36027,Dutchess,2986,13,8,8.6,117,12198,0.002653
14,2019,36029,Erie,11652,16,9,7.9,241,33803,0.002778
15,2019,36031,Essex,513,13,7,8.8,17,1491,0.001397
16,2019,36033,Franklin,631,15,8,7.6,19,2434,0.002584
17,2019,36035,Fulton,785,17,7,8.2,24,2528,0.001597
18,2019,36037,Genesee,722,17,6,8.8,39,2472,0.001536
19,2019,36039,Greene,681,16,8,8.3,38,2001,0.000822
20,2019,36041,Hamilton,75,12,5,7.8,3,217,0.000446
22,2019,36045,Jefferson,1199,17,7,7.8,45,5656,0.001805
23,2019,36047,Kings,21908,18,8,7.4,343,198931,0.001980
24,2019,36049,Lewis,307,13,7,8.1,22,1307,0.002110
25,2019,36051,Livingston,659,14,6,8.3,26,2210,0.000972
26,2019,36053,Madison,759,13,6,8.8,33,2682,0.001776
27,2019,36055,Monroe,7677,15,8,7.9,203,29587,0.002500
28,2019,36057,Montgomery,669,16,7,7.8,25,2372,0.000792
29,2019,36059,Nassau,10768,12,8,9.7,417,56454,0.002841
30,2019,36061,New York,11857,15,8,8.3,198,85635,0.007874
31,2019,36063,Niagara,3022,16,8,8.2,95,8540,0.001046
32,2019,36065,Oneida,3000,16,8,8.1,88,8892,0.001527
33,2019,36067,Onondaga,5174,14,8,8.1,149,19703,0.002299
34,2019,36069,Ontario,1287,13,7,8.6,60,3911,0.002037
35,2019,36071,Orange,3602,16,7,8.8,166,19544,0.002212
36,2019,36073,Orleans,533,18,7,8.1,26,2053,0.000537
37,2019,36075,Oswego,1572,16,7,8.1,94,5083,0.001292
38,2019,36077,Otsego,729,15,7,7.9,26,2670,0.001912
39,2019,36079,Putnam,943,11,8,9.4,32,3959,0.002967
40,2019,36081,Queens,17755,18,8,8.8,383,225096,0.001471
41,2019,36083,Rensselaer,1849,14,8,8.3,47,6332,0.001546
42,2019,36085,Richmond,4902,18,8,9.1,83,21728,0.002101
43,2019,36087,Rockland,2372,14,6,8.8,78,17759,0.002500
44,2019,36089,St. Lawrence,1350,17,7,7.7,56,5360,0.001825
45,2019,36091,Saratoga,2265,11,7,8.9,84,8005,0.001563
46,2019,36093,Schenectady,1852,14,8,8.3,36,6130,0.002083
47,2019,36095,Schoharie,395,14,7,8.1,12,1353,0.001209
48,2019,36097,Schuyler,274,17,7,8.4,12,804,0.001610
49,2019,36099,Seneca,465,15,6,8.3,26,1649,0.001709
51,2019,36103,Suffolk,14659,14,8,9.4,696,74327,0.002532
52,2019,36105,Sullivan,1106,19,9,8.3,55,4087,0.001894
53,2019,36107,Tioga,578,15,7,8.8,19,1869,0.001420
54,2019,36109,Tompkins,883,15,6,7.8,47,4429,0.003390
55,2019,36111,Ulster,2216,14,7,8.2,89,9049,0.003236
56,2019,36113,Warren,889,11,7,8.5,25,2623,0.003663
57,2019,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,2019,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,2019,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,2019,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,2019,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [18]:
clean_data.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                            int64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [19]:
# Spliting the Mental Health Provider Ratio 
changing = clean_data['Mental Health Provider Ratio'].str.split(':', expand=True)
changing.dtypes

AttributeError: Can only use .str accessor with string values!

In [20]:
# Converting the string into int
changing = changing.astype('int')

NameError: name 'changing' is not defined

In [21]:
# Changing the Mental Health Provider Ratio into a int value
clean_data['Mental Health Provider Ratio'] = changing[1]/changing[0]
clean_data

NameError: name 'changing' is not defined

In [22]:
clean_data.shape

(60, 10)

In [23]:
clean_data.head(60)

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2019,36001,Albany,3202,13,8,8.1,100,10741,0.003344
1,2019,36003,Allegany,596,15,7,8.2,18,1936,0.001919
2,2019,36005,Bronx,14817,27,9,7.8,216,116497,0.001866
3,2019,36007,Broome,2442,17,8,8.1,66,8158,0.001927
4,2019,36009,Cattaraugus,1095,19,8,8.2,38,4441,0.001112
5,2019,36011,Cayuga,955,14,6,8.7,38,3361,0.001701
6,2019,36013,Chautauqua,1889,18,7,7.9,53,5619,0.001488
7,2019,36015,Chemung,1256,16,7,7.9,31,3076,0.002755
8,2019,36017,Chenango,734,16,7,8.6,30,1985,0.001923
9,2019,36019,Clinton,898,15,7,7.6,30,3798,0.002309
10,2019,36021,Columbia,846,12,6,8.5,42,2991,0.001667
11,2019,36023,Cortland,608,16,7,8.3,30,1702,0.003185
12,2019,36025,Delaware,655,15,7,8.6,32,2160,0.001156
13,2019,36027,Dutchess,2986,13,8,8.6,117,12198,0.002653
14,2019,36029,Erie,11652,16,9,7.9,241,33803,0.002778
15,2019,36031,Essex,513,13,7,8.8,17,1491,0.001397
16,2019,36033,Franklin,631,15,8,7.6,19,2434,0.002584
17,2019,36035,Fulton,785,17,7,8.2,24,2528,0.001597
18,2019,36037,Genesee,722,17,6,8.8,39,2472,0.001536
19,2019,36039,Greene,681,16,8,8.3,38,2001,0.000822
20,2019,36041,Hamilton,75,12,5,7.8,3,217,0.000446
22,2019,36045,Jefferson,1199,17,7,7.8,45,5656,0.001805
23,2019,36047,Kings,21908,18,8,7.4,343,198931,0.001980
24,2019,36049,Lewis,307,13,7,8.1,22,1307,0.002110
25,2019,36051,Livingston,659,14,6,8.3,26,2210,0.000972
26,2019,36053,Madison,759,13,6,8.8,33,2682,0.001776
27,2019,36055,Monroe,7677,15,8,7.9,203,29587,0.002500
28,2019,36057,Montgomery,669,16,7,7.8,25,2372,0.000792
29,2019,36059,Nassau,10768,12,8,9.7,417,56454,0.002841
30,2019,36061,New York,11857,15,8,8.3,198,85635,0.007874
31,2019,36063,Niagara,3022,16,8,8.2,95,8540,0.001046
32,2019,36065,Oneida,3000,16,8,8.1,88,8892,0.001527
33,2019,36067,Onondaga,5174,14,8,8.1,149,19703,0.002299
34,2019,36069,Ontario,1287,13,7,8.6,60,3911,0.002037
35,2019,36071,Orange,3602,16,7,8.8,166,19544,0.002212
36,2019,36073,Orleans,533,18,7,8.1,26,2053,0.000537
37,2019,36075,Oswego,1572,16,7,8.1,94,5083,0.001292
38,2019,36077,Otsego,729,15,7,7.9,26,2670,0.001912
39,2019,36079,Putnam,943,11,8,9.4,32,3959,0.002967
40,2019,36081,Queens,17755,18,8,8.8,383,225096,0.001471
41,2019,36083,Rensselaer,1849,14,8,8.3,47,6332,0.001546
42,2019,36085,Richmond,4902,18,8,9.1,83,21728,0.002101
43,2019,36087,Rockland,2372,14,6,8.8,78,17759,0.002500
44,2019,36089,St. Lawrence,1350,17,7,7.7,56,5360,0.001825
45,2019,36091,Saratoga,2265,11,7,8.9,84,8005,0.001563
46,2019,36093,Schenectady,1852,14,8,8.3,36,6130,0.002083
47,2019,36095,Schoharie,395,14,7,8.1,12,1353,0.001209
48,2019,36097,Schuyler,274,17,7,8.4,12,804,0.001610
49,2019,36099,Seneca,465,15,6,8.3,26,1649,0.001709
51,2019,36103,Suffolk,14659,14,8,9.4,696,74327,0.002532
52,2019,36105,Sullivan,1106,19,9,8.3,55,4087,0.001894
53,2019,36107,Tioga,578,15,7,8.8,19,1869,0.001420
54,2019,36109,Tompkins,883,15,6,7.8,47,4429,0.003390
55,2019,36111,Ulster,2216,14,7,8.2,89,9049,0.003236
56,2019,36113,Warren,889,11,7,8.5,25,2623,0.003663
57,2019,36115,Washington,796,14,7,8.4,37,2636,0.001362
58,2019,36117,Wayne,1197,16,7,8.6,54,3992,0.000937
59,2019,36119,Westchester,7174,14,8,9.2,199,61342,0.003636
60,2019,36121,Wyoming,509,16,6,8.3,22,1632,0.002000
61,2019,36123,Yates,281,13,5,8.9,10,1816,0.001082

In [24]:
#convert all objects to integer
df = pd.DataFrame(clean_data)
df = df.astype({"FIPS":"int",
                        "Years":"object",
                        "Deaths":"int",
                        "% Fair or Poor Health":"int",
                        "% Low birthweight":"int",
                        "# Driving Deaths":"int",
                        "# Uninsured":"int"})

In [25]:

df.dtypes

Years                            object
FIPS                              int32
County                           object
Deaths                            int32
% Fair or Poor Health             int32
% Low birthweight                 int32
Food Environment Index          float64
# Driving Deaths                  int32
# Uninsured                       int32
Mental Health Provider Ratio    float64
dtype: object

In [20]:
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2018,36001,Albany,3047,13,8,8.0,99,13476,0.003155
1,2018,36003,Allegany,541,15,7,8.2,21,2165,0.001912
2,2018,36005,Bronx,14696,27,9,7.9,227,139181,0.001795
3,2018,36007,Broome,2395,17,8,8.0,66,9823,0.001869
4,2018,36009,Cattaraugus,1043,19,8,8.1,32,4693,0.001107
5,2018,36011,Cayuga,930,14,7,8.5,37,4102,0.001631
6,2018,36013,Chautauqua,1830,18,8,7.8,61,6755,0.001404
7,2018,36015,Chemung,1184,16,7,7.8,34,3462,0.002500
8,2018,36017,Chenango,714,16,7,8.5,33,2534,0.001873
9,2018,36019,Clinton,908,15,7,7.5,34,4261,0.002123
10,2018,36021,Columbia,801,12,6,8.4,36,3408,0.001608
11,2018,36023,Cortland,588,16,7,8.2,29,1962,0.003040
12,2018,36025,Delaware,636,15,7,8.5,34,2458,0.001099
13,2018,36027,Dutchess,2889,13,7,8.6,113,14530,0.002545
14,2018,36029,Erie,11515,16,8,7.8,254,40592,0.002469
15,2018,36031,Essex,513,13,7,8.6,22,1941,0.001443
16,2018,36033,Franklin,602,15,8,7.4,25,2911,0.002500
17,2018,36035,Fulton,780,17,7,8.1,20,2916,0.001171
18,2018,36037,Genesee,662,17,6,8.6,37,2752,0.001351
19,2018,36039,Greene,689,16,8,8.2,37,2441,0.000758
20,2018,36041,Hamilton,71,12,5,7.7,4,254,0.000440
22,2018,36045,Jefferson,1186,17,7,7.6,63,6347,0.001754
23,2018,36047,Kings,21622,18,8,7.4,363,233136,0.001880
24,2018,36049,Lewis,310,13,7,8.1,23,1578,0.002160
25,2018,36051,Livingston,623,14,6,8.2,29,2788,0.000856
26,2018,36053,Madison,819,13,7,8.6,32,3109,0.001585
27,2018,36055,Monroe,7553,15,8,7.8,195,33894,0.002283
28,2018,36057,Montgomery,625,16,7,7.8,22,3011,0.000751
29,2018,36059,Nassau,10712,12,8,9.7,431,73340,0.002740
30,2018,36061,New York,11880,15,8,8.3,204,106584,0.007634
31,2018,36063,Niagara,3013,16,8,8.1,94,9453,0.001025
32,2018,36065,Oneida,2878,16,8,8.0,84,10958,0.001466
33,2018,36067,Onondaga,5132,14,8,8.0,144,22210,0.002165
34,2018,36069,Ontario,1247,13,7,8.5,75,4942,0.001938
35,2018,36071,Orange,3528,16,7,8.7,171,20735,0.002092
36,2018,36073,Orleans,520,18,7,8.0,19,2277,0.000460
37,2018,36075,Oswego,1530,16,7,8.0,101,6351,0.001218
38,2018,36077,Otsego,704,15,6,7.8,24,2840,0.001698
39,2018,36079,Putnam,911,11,8,9.3,36,4559,0.002841
40,2018,36081,Queens,17633,18,8,8.7,407,258703,0.001403
41,2018,36083,Rensselaer,1848,14,8,8.3,49,6795,0.001486
42,2018,36085,Richmond,4799,18,8,9.1,90,25696,0.002028
43,2018,36087,Rockland,2280,14,6,8.8,75,20496,0.002481
44,2018,36089,St. Lawrence,1310,17,7,7.6,55,5614,0.001754
45,2018,36091,Saratoga,2169,11,7,8.8,88,9221,0.001488
46,2018,36093,Schenectady,1791,14,8,8.1,34,7248,0.001992
47,2018,36095,Schoharie,399,14,7,8.2,14,1488,0.001117
48,2018,36097,Schuyler,250,17,7,8.3,11,942,0.001603
49,2018,36099,Seneca,462,15,6,8.1,29,1826,0.001667
51,2018,36103,Suffolk,14354,14,8,9.4,715,86917,0.002433
52,2018,36105,Sullivan,1103,19,9,8.2,61,5260,0.001832
53,2018,36107,Tioga,590,15,7,8.7,25,2186,0.001374
54,2018,36109,Tompkins,816,15,7,7.7,52,5055,0.003195
55,2018,36111,Ulster,2184,14,7,8.1,77,10680,0.003185
56,2018,36113,Warren,863,11,6,8.4,23,2993,0.003448
57,2018,36115,Washington,771,14,8,8.3,43,3020,0.001263
58,2018,36117,Wayne,1146,16,7,8.5,56,4819,0.000892
59,2018,36119,Westchester,7149,14,8,9.2,196,66058,0.003497
60,2018,36121,Wyoming,504,16,6,8.2,19,1863,0.001789
61,2018,36123,Yates,277,13,5,8.7,17,1863,0.001003

In [27]:
# Saving the new and cleaned dataset
file_path = "2019_clean_dataset.csv"
clean_data.to_csv(file_path, index=False)