In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading in Data
df = pd.read_csv('2020_county_health_dataset.csv')
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
...,...,...,...,...,...,...,...,...,...,...
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [3]:
# Selecting the columns we only want
select_df = df[['FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [4]:
# Removing the first row that was NaN 
select_df = select_df.dropna(how='all')
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [5]:

select_df.head(60)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
21,36043,Herkimer,796.0,16,7,7.9,32,2411,0.000485
22,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066
23,36047,Kings,21917.0,18,8,7.5,312,179878,0.002193
24,36049,Lewis,295.0,14,7,8.0,18,1269,0.002119
25,36051,Livingston,716.0,15,6,8.2,28,2095,0.001171
26,36053,Madison,743.0,13,7,8.7,30,2708,0.001976
27,36055,Monroe,7898.0,14,8,7.9,210,28214,0.002747
28,36057,Montgomery,686.0,17,7,7.8,21,2462,0.000849
29,36059,Nassau,10857.0,12,8,9.7,394,60098,0.003021
30,36061,New York,11804.0,16,8,8.3,180,83332,0.008621
31,36063,Niagara,3073.0,14,8,8.1,82,8640,0.001112
32,36065,Oneida,3070.0,16,8,8.0,88,10140,0.001642
33,36067,Onondaga,5156.0,14,8,8.1,152,18885,0.002532
34,36069,Ontario,1322.0,13,7,8.5,58,3824,0.002155
35,36071,Orange,3697.0,15,7,8.7,161,18227,0.002358
36,36073,Orleans,570.0,16,7,8.0,20,1754,0.000542
37,36075,Oswego,1612.0,15,7,8.0,81,5016,0.001357
38,36077,Otsego,745.0,15,7,7.8,22,2245,0.001923
39,36079,Putnam,918.0,12,8,9.3,32,4031,0.003401
40,36081,Queens,17867.0,19,8,8.7,353,202448,0.001626
41,36083,Rensselaer,1896.0,15,8,8.2,42,5856,0.001661
42,36085,Richmond,4900.0,15,8,9.1,78,19801,0.002294
43,36087,Rockland,2420.0,17,6,8.7,71,16379,0.002625
44,36089,St. Lawrence,1373.0,18,7,7.6,47,5093,0.001961
45,36091,Saratoga,2325.0,11,6,8.9,80,7118,0.001650
46,36093,Schenectady,1827.0,15,8,8.2,39,6144,0.002232
47,36095,Schoharie,397.0,15,7,8.1,38,1226,0.001319
48,36097,Schuyler,268.0,15,6,8.3,10,747,0.001675
49,36099,Seneca,472.0,15,6,8.2,23,1606,0.001808
50,36101,Steuben,1302.0,16,7,8.3,42,4695,0.001828
51,36103,Suffolk,14740.0,13,8,9.3,684,67541,0.002667
52,36105,Sullivan,1109.0,17,8,8.3,55,3883,0.001894
53,36107,Tioga,565.0,14,7,8.6,19,1843,0.001359
54,36109,Tompkins,866.0,14,7,7.7,42,4160,0.003704
55,36111,Ulster,2199.0,16,7,8.1,77,9437,0.003436
56,36113,Warren,857.0,13,7,8.5,27,2628,0.003817
57,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876

In [6]:
# Removing the row that was NaN 
select_df = select_df.drop(labels=21, axis=0)
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [7]:
# Removing the row that was NaN
# Also drop First Row (NY State)
select_df = select_df.drop(labels=62, axis=0)
select_df = select_df.drop(labels=0, axis=0)

select_df

KeyError: '[62] not found in axis'

In [8]:
select_df.head(22)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
22,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066

In [10]:
# The the year for the dataset
#select_df["Years"] = "2020"
select_df["Years"] = 2020

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio,Years
0,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559,2020
1,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217,2020
2,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058,2020
3,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132,2020
4,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250,2020
...,...,...,...,...,...,...,...,...,...,...
57,36115,Washington,821.0,14,7,8.4,36,2629,0.001404,2020
58,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044,2020
59,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876,2020
60,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146,2020
61,36123,Yates,305.0,15,5,8.8,12,1587,0.001208,2020

In [11]:
# Reorganizing the dataset
clean_data = select_df[['Years', 'FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
...,...,...,...,...,...,...,...,...,...,...
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [12]:
#Drop row 50 (NaN)

# Removing the row that was NaN
# Also drop First Row (NY State)
clean_data = clean_data.drop(labels=50, axis=0)
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,2020,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,2020,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,2020,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,2020,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,2020,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,2020,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,2020,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,2020,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,2020,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,2020,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,2020,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,2020,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,2020,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,2020,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,2020,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,2020,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
22,2020,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066
23,2020,36047,Kings,21917.0,18,8,7.5,312,179878,0.002193
24,2020,36049,Lewis,295.0,14,7,8.0,18,1269,0.002119
25,2020,36051,Livingston,716.0,15,6,8.2,28,2095,0.001171
26,2020,36053,Madison,743.0,13,7,8.7,30,2708,0.001976
27,2020,36055,Monroe,7898.0,14,8,7.9,210,28214,0.002747
28,2020,36057,Montgomery,686.0,17,7,7.8,21,2462,0.000849
29,2020,36059,Nassau,10857.0,12,8,9.7,394,60098,0.003021
30,2020,36061,New York,11804.0,16,8,8.3,180,83332,0.008621
31,2020,36063,Niagara,3073.0,14,8,8.1,82,8640,0.001112
32,2020,36065,Oneida,3070.0,16,8,8.0,88,10140,0.001642
33,2020,36067,Onondaga,5156.0,14,8,8.1,152,18885,0.002532
34,2020,36069,Ontario,1322.0,13,7,8.5,58,3824,0.002155
35,2020,36071,Orange,3697.0,15,7,8.7,161,18227,0.002358
36,2020,36073,Orleans,570.0,16,7,8.0,20,1754,0.000542
37,2020,36075,Oswego,1612.0,15,7,8.0,81,5016,0.001357
38,2020,36077,Otsego,745.0,15,7,7.8,22,2245,0.001923
39,2020,36079,Putnam,918.0,12,8,9.3,32,4031,0.003401
40,2020,36081,Queens,17867.0,19,8,8.7,353,202448,0.001626
41,2020,36083,Rensselaer,1896.0,15,8,8.2,42,5856,0.001661
42,2020,36085,Richmond,4900.0,15,8,9.1,78,19801,0.002294
43,2020,36087,Rockland,2420.0,17,6,8.7,71,16379,0.002625
44,2020,36089,St. Lawrence,1373.0,18,7,7.6,47,5093,0.001961
45,2020,36091,Saratoga,2325.0,11,6,8.9,80,7118,0.001650
46,2020,36093,Schenectady,1827.0,15,8,8.2,39,6144,0.002232
47,2020,36095,Schoharie,397.0,15,7,8.1,38,1226,0.001319
48,2020,36097,Schuyler,268.0,15,6,8.3,10,747,0.001675
49,2020,36099,Seneca,472.0,15,6,8.2,23,1606,0.001808
51,2020,36103,Suffolk,14740.0,13,8,9.3,684,67541,0.002667
52,2020,36105,Sullivan,1109.0,17,8,8.3,55,3883,0.001894
53,2020,36107,Tioga,565.0,14,7,8.6,19,1843,0.001359
54,2020,36109,Tompkins,866.0,14,7,7.7,42,4160,0.003704
55,2020,36111,Ulster,2199.0,16,7,8.1,77,9437,0.003436
56,2020,36113,Warren,857.0,13,7,8.5,27,2628,0.003817
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [13]:
clean_data.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                          float64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [14]:
# Spliting the Mental Health Provider Ratio 
changing = clean_data['Mental Health Provider Ratio'].str.split(':', expand=True)
changing.dtypes

AttributeError: Can only use .str accessor with string values!

In [15]:
# Converting the string into int
changing = changing.astype('int')

NameError: name 'changing' is not defined

In [16]:
# Changing the Mental Health Provider Ratio into a int value
clean_data['Mental Health Provider Ratio'] = changing[1]/changing[0]
clean_data

NameError: name 'changing' is not defined

In [17]:
clean_data.shape

(60, 10)

In [18]:
clean_data.head(60)

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,2020,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,2020,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,2020,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,2020,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,2020,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,2020,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,2020,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,2020,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,2020,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,2020,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,2020,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,2020,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,2020,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,2020,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,2020,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,2020,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
22,2020,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066
23,2020,36047,Kings,21917.0,18,8,7.5,312,179878,0.002193
24,2020,36049,Lewis,295.0,14,7,8.0,18,1269,0.002119
25,2020,36051,Livingston,716.0,15,6,8.2,28,2095,0.001171
26,2020,36053,Madison,743.0,13,7,8.7,30,2708,0.001976
27,2020,36055,Monroe,7898.0,14,8,7.9,210,28214,0.002747
28,2020,36057,Montgomery,686.0,17,7,7.8,21,2462,0.000849
29,2020,36059,Nassau,10857.0,12,8,9.7,394,60098,0.003021
30,2020,36061,New York,11804.0,16,8,8.3,180,83332,0.008621
31,2020,36063,Niagara,3073.0,14,8,8.1,82,8640,0.001112
32,2020,36065,Oneida,3070.0,16,8,8.0,88,10140,0.001642
33,2020,36067,Onondaga,5156.0,14,8,8.1,152,18885,0.002532
34,2020,36069,Ontario,1322.0,13,7,8.5,58,3824,0.002155
35,2020,36071,Orange,3697.0,15,7,8.7,161,18227,0.002358
36,2020,36073,Orleans,570.0,16,7,8.0,20,1754,0.000542
37,2020,36075,Oswego,1612.0,15,7,8.0,81,5016,0.001357
38,2020,36077,Otsego,745.0,15,7,7.8,22,2245,0.001923
39,2020,36079,Putnam,918.0,12,8,9.3,32,4031,0.003401
40,2020,36081,Queens,17867.0,19,8,8.7,353,202448,0.001626
41,2020,36083,Rensselaer,1896.0,15,8,8.2,42,5856,0.001661
42,2020,36085,Richmond,4900.0,15,8,9.1,78,19801,0.002294
43,2020,36087,Rockland,2420.0,17,6,8.7,71,16379,0.002625
44,2020,36089,St. Lawrence,1373.0,18,7,7.6,47,5093,0.001961
45,2020,36091,Saratoga,2325.0,11,6,8.9,80,7118,0.001650
46,2020,36093,Schenectady,1827.0,15,8,8.2,39,6144,0.002232
47,2020,36095,Schoharie,397.0,15,7,8.1,38,1226,0.001319
48,2020,36097,Schuyler,268.0,15,6,8.3,10,747,0.001675
49,2020,36099,Seneca,472.0,15,6,8.2,23,1606,0.001808
51,2020,36103,Suffolk,14740.0,13,8,9.3,684,67541,0.002667
52,2020,36105,Sullivan,1109.0,17,8,8.3,55,3883,0.001894
53,2020,36107,Tioga,565.0,14,7,8.6,19,1843,0.001359
54,2020,36109,Tompkins,866.0,14,7,7.7,42,4160,0.003704
55,2020,36111,Ulster,2199.0,16,7,8.1,77,9437,0.003436
56,2020,36113,Warren,857.0,13,7,8.5,27,2628,0.003817
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [19]:
#convert all objects to integer
df = pd.DataFrame(clean_data)
df = df.astype({"FIPS":"int",
                        "Years":"object",
                        "Deaths":"int",
                        "% Fair or Poor Health":"int",
                        "% Low birthweight":"int",
                        "# Driving Deaths":"int",
                        "# Uninsured":"int"})

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [20]:

df.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                          float64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [21]:
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,2020,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,2020,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,2020,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,2020,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,2020,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,2020,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,2020,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,2020,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,2020,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,2020,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,2020,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,2020,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,2020,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,2020,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,2020,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,2020,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
22,2020,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066
23,2020,36047,Kings,21917.0,18,8,7.5,312,179878,0.002193
24,2020,36049,Lewis,295.0,14,7,8.0,18,1269,0.002119
25,2020,36051,Livingston,716.0,15,6,8.2,28,2095,0.001171
26,2020,36053,Madison,743.0,13,7,8.7,30,2708,0.001976
27,2020,36055,Monroe,7898.0,14,8,7.9,210,28214,0.002747
28,2020,36057,Montgomery,686.0,17,7,7.8,21,2462,0.000849
29,2020,36059,Nassau,10857.0,12,8,9.7,394,60098,0.003021
30,2020,36061,New York,11804.0,16,8,8.3,180,83332,0.008621
31,2020,36063,Niagara,3073.0,14,8,8.1,82,8640,0.001112
32,2020,36065,Oneida,3070.0,16,8,8.0,88,10140,0.001642
33,2020,36067,Onondaga,5156.0,14,8,8.1,152,18885,0.002532
34,2020,36069,Ontario,1322.0,13,7,8.5,58,3824,0.002155
35,2020,36071,Orange,3697.0,15,7,8.7,161,18227,0.002358
36,2020,36073,Orleans,570.0,16,7,8.0,20,1754,0.000542
37,2020,36075,Oswego,1612.0,15,7,8.0,81,5016,0.001357
38,2020,36077,Otsego,745.0,15,7,7.8,22,2245,0.001923
39,2020,36079,Putnam,918.0,12,8,9.3,32,4031,0.003401
40,2020,36081,Queens,17867.0,19,8,8.7,353,202448,0.001626
41,2020,36083,Rensselaer,1896.0,15,8,8.2,42,5856,0.001661
42,2020,36085,Richmond,4900.0,15,8,9.1,78,19801,0.002294
43,2020,36087,Rockland,2420.0,17,6,8.7,71,16379,0.002625
44,2020,36089,St. Lawrence,1373.0,18,7,7.6,47,5093,0.001961
45,2020,36091,Saratoga,2325.0,11,6,8.9,80,7118,0.001650
46,2020,36093,Schenectady,1827.0,15,8,8.2,39,6144,0.002232
47,2020,36095,Schoharie,397.0,15,7,8.1,38,1226,0.001319
48,2020,36097,Schuyler,268.0,15,6,8.3,10,747,0.001675
49,2020,36099,Seneca,472.0,15,6,8.2,23,1606,0.001808
51,2020,36103,Suffolk,14740.0,13,8,9.3,684,67541,0.002667
52,2020,36105,Sullivan,1109.0,17,8,8.3,55,3883,0.001894
53,2020,36107,Tioga,565.0,14,7,8.6,19,1843,0.001359
54,2020,36109,Tompkins,866.0,14,7,7.7,42,4160,0.003704
55,2020,36111,Ulster,2199.0,16,7,8.1,77,9437,0.003436
56,2020,36113,Warren,857.0,13,7,8.5,27,2628,0.003817
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [23]:
# Saving the new and cleaned dataset
file_path = "2020_clean_dataset.csv"
clean_data.to_csv(file_path, index=False)