In [2]:
import pandas as pd
import numpy as np

In [3]:
# Reading in Data
df = pd.read_csv('2022_counthy_health_dataset.csv')
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2022,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,2022,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,2022,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,2022,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,2022,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
...,...,...,...,...,...,...,...,...,...,...
57,2022,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,2022,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,2022,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,2022,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,2022,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [4]:
# Selecting the columns we only want
select_df = df[['FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [5]:
# Removing the first row that was NaN 
select_df = select_df.dropna(how='all')
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [6]:

select_df.head(60)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
5,36011,Cayuga,1063.0,18,7,8.5,37,2770,0.002066
6,36013,Chautauqua,1889.0,20,8,7.6,53,5210,0.001818
7,36015,Chemung,1377.0,18,8,7.9,28,2636,0.003115
8,36017,Chenango,752.0,19,7,8.2,32,1703,0.001969
9,36019,Clinton,1034.0,18,7,8.0,29,3018,0.003049
10,36021,Columbia,819.0,16,6,8.1,37,2524,0.002000
11,36023,Cortland,620.0,17,8,8.0,15,1506,0.003745
12,36025,Delaware,691.0,19,6,7.8,31,1789,0.001342
13,36027,Dutchess,3387.0,16,8,8.6,107,12124,0.003106
14,36029,Erie,12400.0,17,9,8.1,224,29797,0.003509
15,36031,Essex,522.0,16,7,8.6,20,1308,0.001653
16,36033,Franklin,643.0,20,7,7.4,17,2492,0.003058
17,36035,Fulton,831.0,19,8,7.9,22,2014,0.002331
18,36037,Genesee,774.0,17,6,8.6,48,1985,0.001631
19,36039,Greene,720.0,19,7,8.4,34,1687,0.000912
20,36041,Hamilton,NaN,20,6,7.1,4,218,0.000691
21,36043,Herkimer,845.0,18,7,8.0,32,2237,0.000787
22,36045,Jefferson,1275.0,19,7,7.6,45,4191,0.002347
23,36047,Kings,25999.0,20,8,8.2,297,155196,0.002538
24,36049,Lewis,292.0,18,7,8.1,16,1047,0.002212
25,36051,Livingston,715.0,17,7,8.5,26,2114,0.001314
26,36053,Madison,764.0,16,7,8.4,29,2311,0.002114
27,36055,Monroe,8452.0,17,9,8.0,222,24849,0.003135
28,36057,Montgomery,722.0,22,8,6.2,19,2044,0.000875
29,36059,Nassau,12063.0,14,8,9.9,367,53385,0.003356
30,36061,New York,13274.0,17,8,8.4,180,73874,0.009615
31,36063,Niagara,3213.0,17,8,8.0,83,7153,0.001391
32,36065,Oneida,3327.0,18,8,7.9,89,9299,0.001866
33,36067,Onondaga,5458.0,16,8,8.1,140,17751,0.002907
34,36069,Ontario,1302.0,14,7,8.7,46,3475,0.002427
35,36071,Orange,3969.0,17,7,8.5,155,15775,0.002564
36,36073,Orleans,616.0,20,7,8.2,24,1817,0.000650
37,36075,Oswego,1585.0,19,7,8.0,79,4904,0.001538
38,36077,Otsego,752.0,17,6,7.5,17,2160,0.002096
39,36079,Putnam,896.0,14,7,9.0,27,3369,0.003922
40,36081,Queens,22297.0,21,8,9.0,341,191502,0.001848
41,36083,Rensselaer,2025.0,15,8,8.3,39,5339,0.001789
42,36085,Richmond,5412.0,18,8,9.2,57,19502,0.002500
43,36087,Rockland,2882.0,17,6,8.7,69,15161,0.002967
44,36089,St. Lawrence,1393.0,19,7,7.3,45,4451,0.002174
45,36091,Saratoga,2377.0,13,7,8.9,86,6612,0.001988
46,36093,Schenectady,1903.0,17,9,8.6,41,6032,0.002494
47,36095,Schoharie,421.0,17,7,8.5,40,1160,0.001412
48,36097,Schuyler,243.0,18,5,8.2,9,665,0.001866
49,36099,Seneca,477.0,19,6,8.4,22,1362,0.001942
50,36101,Steuben,1387.0,18,7,8.0,46,3881,0.002101
51,36103,Suffolk,15878.0,15,8,9.3,621,62909,0.002933
52,36105,Sullivan,1184.0,20,8,8.3,46,3685,0.001953
53,36107,Tioga,614.0,17,7,8.7,32,1621,0.001565
54,36109,Tompkins,805.0,15,6,8.0,34,3475,0.004132
55,36111,Ulster,2292.0,17,7,8.1,88,7976,0.003745
56,36113,Warren,844.0,15,7,8.2,27,2128,0.004082
57,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274

In [7]:
# Removing the row that was NaN 
select_df = select_df.drop(labels=21, axis=0)
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
...,...,...,...,...,...,...,...,...,...
57,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [8]:
# Removing the row that was NaN
# Also drop First Row (NY State)
select_df = select_df.drop(labels=62, axis=0)
select_df = select_df.drop(labels=0, axis=0)

select_df

KeyError: '[62] not found in axis'

In [9]:
select_df.head(22)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
5,36011,Cayuga,1063.0,18,7,8.5,37,2770,0.002066
6,36013,Chautauqua,1889.0,20,8,7.6,53,5210,0.001818
7,36015,Chemung,1377.0,18,8,7.9,28,2636,0.003115
8,36017,Chenango,752.0,19,7,8.2,32,1703,0.001969
9,36019,Clinton,1034.0,18,7,8.0,29,3018,0.003049
10,36021,Columbia,819.0,16,6,8.1,37,2524,0.002000
11,36023,Cortland,620.0,17,8,8.0,15,1506,0.003745
12,36025,Delaware,691.0,19,6,7.8,31,1789,0.001342
13,36027,Dutchess,3387.0,16,8,8.6,107,12124,0.003106
14,36029,Erie,12400.0,17,9,8.1,224,29797,0.003509
15,36031,Essex,522.0,16,7,8.6,20,1308,0.001653
16,36033,Franklin,643.0,20,7,7.4,17,2492,0.003058
17,36035,Fulton,831.0,19,8,7.9,22,2014,0.002331
18,36037,Genesee,774.0,17,6,8.6,48,1985,0.001631
19,36039,Greene,720.0,19,7,8.4,34,1687,0.000912
20,36041,Hamilton,NaN,20,6,7.1,4,218,0.000691
22,36045,Jefferson,1275.0,19,7,7.6,45,4191,0.002347

In [10]:
# The the year for the dataset
#select_df["Years"] = "2022"
select_df["Years"] = 2022

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio,Years
0,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000,2022
1,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481,2022
2,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315,2022
3,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353,2022
4,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490,2022
...,...,...,...,...,...,...,...,...,...,...
57,36115,Washington,882.0,18,7,8.5,29,2344,0.001502,2022
58,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130,2022
59,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274,2022
60,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304,2022
61,36123,Yates,339.0,18,4,8.9,10,1520,0.001171,2022

In [11]:
# Reorganizing the dataset
clean_data = select_df[['Years', 'FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2022,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,2022,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,2022,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,2022,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,2022,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
...,...,...,...,...,...,...,...,...,...,...
57,2022,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,2022,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,2022,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,2022,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,2022,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [12]:
#Drop row 50 (NaN)

# Removing the row that was NaN
# Also drop First Row (NY State)
clean_data = clean_data.drop(labels=50, axis=0)
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2022,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,2022,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,2022,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,2022,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,2022,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
5,2022,36011,Cayuga,1063.0,18,7,8.5,37,2770,0.002066
6,2022,36013,Chautauqua,1889.0,20,8,7.6,53,5210,0.001818
7,2022,36015,Chemung,1377.0,18,8,7.9,28,2636,0.003115
8,2022,36017,Chenango,752.0,19,7,8.2,32,1703,0.001969
9,2022,36019,Clinton,1034.0,18,7,8.0,29,3018,0.003049
10,2022,36021,Columbia,819.0,16,6,8.1,37,2524,0.002000
11,2022,36023,Cortland,620.0,17,8,8.0,15,1506,0.003745
12,2022,36025,Delaware,691.0,19,6,7.8,31,1789,0.001342
13,2022,36027,Dutchess,3387.0,16,8,8.6,107,12124,0.003106
14,2022,36029,Erie,12400.0,17,9,8.1,224,29797,0.003509
15,2022,36031,Essex,522.0,16,7,8.6,20,1308,0.001653
16,2022,36033,Franklin,643.0,20,7,7.4,17,2492,0.003058
17,2022,36035,Fulton,831.0,19,8,7.9,22,2014,0.002331
18,2022,36037,Genesee,774.0,17,6,8.6,48,1985,0.001631
19,2022,36039,Greene,720.0,19,7,8.4,34,1687,0.000912
20,2022,36041,Hamilton,NaN,20,6,7.1,4,218,0.000691
22,2022,36045,Jefferson,1275.0,19,7,7.6,45,4191,0.002347
23,2022,36047,Kings,25999.0,20,8,8.2,297,155196,0.002538
24,2022,36049,Lewis,292.0,18,7,8.1,16,1047,0.002212
25,2022,36051,Livingston,715.0,17,7,8.5,26,2114,0.001314
26,2022,36053,Madison,764.0,16,7,8.4,29,2311,0.002114
27,2022,36055,Monroe,8452.0,17,9,8.0,222,24849,0.003135
28,2022,36057,Montgomery,722.0,22,8,6.2,19,2044,0.000875
29,2022,36059,Nassau,12063.0,14,8,9.9,367,53385,0.003356
30,2022,36061,New York,13274.0,17,8,8.4,180,73874,0.009615
31,2022,36063,Niagara,3213.0,17,8,8.0,83,7153,0.001391
32,2022,36065,Oneida,3327.0,18,8,7.9,89,9299,0.001866
33,2022,36067,Onondaga,5458.0,16,8,8.1,140,17751,0.002907
34,2022,36069,Ontario,1302.0,14,7,8.7,46,3475,0.002427
35,2022,36071,Orange,3969.0,17,7,8.5,155,15775,0.002564
36,2022,36073,Orleans,616.0,20,7,8.2,24,1817,0.000650
37,2022,36075,Oswego,1585.0,19,7,8.0,79,4904,0.001538
38,2022,36077,Otsego,752.0,17,6,7.5,17,2160,0.002096
39,2022,36079,Putnam,896.0,14,7,9.0,27,3369,0.003922
40,2022,36081,Queens,22297.0,21,8,9.0,341,191502,0.001848
41,2022,36083,Rensselaer,2025.0,15,8,8.3,39,5339,0.001789
42,2022,36085,Richmond,5412.0,18,8,9.2,57,19502,0.002500
43,2022,36087,Rockland,2882.0,17,6,8.7,69,15161,0.002967
44,2022,36089,St. Lawrence,1393.0,19,7,7.3,45,4451,0.002174
45,2022,36091,Saratoga,2377.0,13,7,8.9,86,6612,0.001988
46,2022,36093,Schenectady,1903.0,17,9,8.6,41,6032,0.002494
47,2022,36095,Schoharie,421.0,17,7,8.5,40,1160,0.001412
48,2022,36097,Schuyler,243.0,18,5,8.2,9,665,0.001866
49,2022,36099,Seneca,477.0,19,6,8.4,22,1362,0.001942
51,2022,36103,Suffolk,15878.0,15,8,9.3,621,62909,0.002933
52,2022,36105,Sullivan,1184.0,20,8,8.3,46,3685,0.001953
53,2022,36107,Tioga,614.0,17,7,8.7,32,1621,0.001565
54,2022,36109,Tompkins,805.0,15,6,8.0,34,3475,0.004132
55,2022,36111,Ulster,2292.0,17,7,8.1,88,7976,0.003745
56,2022,36113,Warren,844.0,15,7,8.2,27,2128,0.004082
57,2022,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,2022,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,2022,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,2022,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,2022,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [13]:
clean_data.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                          float64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [14]:
# Spliting the Mental Health Provider Ratio 
changing = clean_data['Mental Health Provider Ratio'].str.split(':', expand=True)
changing.dtypes

AttributeError: Can only use .str accessor with string values!

In [15]:
# Converting the string into int
changing = changing.astype('int')

NameError: name 'changing' is not defined

In [16]:
# Changing the Mental Health Provider Ratio into a int value
clean_data['Mental Health Provider Ratio'] = changing[1]/changing[0]
clean_data

NameError: name 'changing' is not defined

In [17]:
clean_data.shape

(60, 10)

In [18]:
clean_data.head(60)

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2022,36001,Albany,3545.0,15,8,8.3,91,9639,0.004000
1,2022,36003,Allegany,646.0,18,7,8.0,16,1824,0.002481
2,2022,36005,Bronx,18665.0,30,10,7.6,207,100053,0.002315
3,2022,36007,Broome,2598.0,19,8,7.9,61,7520,0.002353
4,2022,36009,Cattaraugus,1224.0,20,8,7.9,41,4088,0.001490
5,2022,36011,Cayuga,1063.0,18,7,8.5,37,2770,0.002066
6,2022,36013,Chautauqua,1889.0,20,8,7.6,53,5210,0.001818
7,2022,36015,Chemung,1377.0,18,8,7.9,28,2636,0.003115
8,2022,36017,Chenango,752.0,19,7,8.2,32,1703,0.001969
9,2022,36019,Clinton,1034.0,18,7,8.0,29,3018,0.003049
10,2022,36021,Columbia,819.0,16,6,8.1,37,2524,0.002000
11,2022,36023,Cortland,620.0,17,8,8.0,15,1506,0.003745
12,2022,36025,Delaware,691.0,19,6,7.8,31,1789,0.001342
13,2022,36027,Dutchess,3387.0,16,8,8.6,107,12124,0.003106
14,2022,36029,Erie,12400.0,17,9,8.1,224,29797,0.003509
15,2022,36031,Essex,522.0,16,7,8.6,20,1308,0.001653
16,2022,36033,Franklin,643.0,20,7,7.4,17,2492,0.003058
17,2022,36035,Fulton,831.0,19,8,7.9,22,2014,0.002331
18,2022,36037,Genesee,774.0,17,6,8.6,48,1985,0.001631
19,2022,36039,Greene,720.0,19,7,8.4,34,1687,0.000912
20,2022,36041,Hamilton,NaN,20,6,7.1,4,218,0.000691
22,2022,36045,Jefferson,1275.0,19,7,7.6,45,4191,0.002347
23,2022,36047,Kings,25999.0,20,8,8.2,297,155196,0.002538
24,2022,36049,Lewis,292.0,18,7,8.1,16,1047,0.002212
25,2022,36051,Livingston,715.0,17,7,8.5,26,2114,0.001314
26,2022,36053,Madison,764.0,16,7,8.4,29,2311,0.002114
27,2022,36055,Monroe,8452.0,17,9,8.0,222,24849,0.003135
28,2022,36057,Montgomery,722.0,22,8,6.2,19,2044,0.000875
29,2022,36059,Nassau,12063.0,14,8,9.9,367,53385,0.003356
30,2022,36061,New York,13274.0,17,8,8.4,180,73874,0.009615
31,2022,36063,Niagara,3213.0,17,8,8.0,83,7153,0.001391
32,2022,36065,Oneida,3327.0,18,8,7.9,89,9299,0.001866
33,2022,36067,Onondaga,5458.0,16,8,8.1,140,17751,0.002907
34,2022,36069,Ontario,1302.0,14,7,8.7,46,3475,0.002427
35,2022,36071,Orange,3969.0,17,7,8.5,155,15775,0.002564
36,2022,36073,Orleans,616.0,20,7,8.2,24,1817,0.000650
37,2022,36075,Oswego,1585.0,19,7,8.0,79,4904,0.001538
38,2022,36077,Otsego,752.0,17,6,7.5,17,2160,0.002096
39,2022,36079,Putnam,896.0,14,7,9.0,27,3369,0.003922
40,2022,36081,Queens,22297.0,21,8,9.0,341,191502,0.001848
41,2022,36083,Rensselaer,2025.0,15,8,8.3,39,5339,0.001789
42,2022,36085,Richmond,5412.0,18,8,9.2,57,19502,0.002500
43,2022,36087,Rockland,2882.0,17,6,8.7,69,15161,0.002967
44,2022,36089,St. Lawrence,1393.0,19,7,7.3,45,4451,0.002174
45,2022,36091,Saratoga,2377.0,13,7,8.9,86,6612,0.001988
46,2022,36093,Schenectady,1903.0,17,9,8.6,41,6032,0.002494
47,2022,36095,Schoharie,421.0,17,7,8.5,40,1160,0.001412
48,2022,36097,Schuyler,243.0,18,5,8.2,9,665,0.001866
49,2022,36099,Seneca,477.0,19,6,8.4,22,1362,0.001942
51,2022,36103,Suffolk,15878.0,15,8,9.3,621,62909,0.002933
52,2022,36105,Sullivan,1184.0,20,8,8.3,46,3685,0.001953
53,2022,36107,Tioga,614.0,17,7,8.7,32,1621,0.001565
54,2022,36109,Tompkins,805.0,15,6,8.0,34,3475,0.004132
55,2022,36111,Ulster,2292.0,17,7,8.1,88,7976,0.003745
56,2022,36113,Warren,844.0,15,7,8.2,27,2128,0.004082
57,2022,36115,Washington,882.0,18,7,8.5,29,2344,0.001502
58,2022,36117,Wayne,1248.0,17,7,8.6,56,3067,0.001130
59,2022,36119,Westchester,8329.0,16,8,9.3,163,45099,0.004274
60,2022,36121,Wyoming,498.0,18,7,8.4,19,1289,0.002304
61,2022,36123,Yates,339.0,18,4,8.9,10,1520,0.001171

In [19]:
#convert all objects to integer
df = pd.DataFrame(clean_data)
df = df.astype({"FIPS":"int",
                        "Years":"object",
                        "Deaths":"int",
                        "% Fair or Poor Health":"int",
                        "% Low birthweight":"int",
                        "# Driving Deaths":"int",
                        "# Uninsured":"int"})

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [20]:

df.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                          float64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index          float64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [21]:
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,2020,36001,Albany,3307.0,14,8,8.0,105,10808,0.003559
1,2020,36003,Allegany,628.0,14,7,8.1,17,2000,0.002217
2,2020,36005,Bronx,15016.0,27,9,7.7,200,110580,0.002058
3,2020,36007,Broome,2426.0,16,8,8.0,68,7961,0.002132
4,2020,36009,Cattaraugus,1113.0,16,8,8.1,34,3956,0.001250
5,2020,36011,Cayuga,979.0,14,6,8.6,40,3030,0.001894
6,2020,36013,Chautauqua,1904.0,18,7,7.8,53,5236,0.001658
7,2020,36015,Chemung,1274.0,15,7,7.8,33,2761,0.002882
8,2020,36017,Chenango,721.0,15,6,8.5,23,1933,0.001957
9,2020,36019,Clinton,953.0,15,7,7.6,29,3308,0.002625
10,2020,36021,Columbia,842.0,14,6,8.5,40,2775,0.001704
11,2020,36023,Cortland,597.0,13,8,8.1,23,1552,0.003497
12,2020,36025,Delaware,677.0,15,7,8.5,30,2145,0.001235
13,2020,36027,Dutchess,3166.0,15,7,8.6,113,12351,0.002833
14,2020,36029,Erie,11768.0,16,9,7.8,228,33373,0.003086
15,2020,36031,Essex,497.0,11,8,8.7,19,1465,0.001555
16,2020,36033,Franklin,634.0,16,7,7.5,24,2699,0.002747
17,2020,36035,Fulton,776.0,16,7,8.2,21,2437,0.001883
18,2020,36037,Genesee,789.0,14,6,8.6,36,2226,0.001618
19,2020,36039,Greene,689.0,14,7,8.2,39,1950,0.000842
20,2020,36041,Hamilton,NaN,14,5,7.7,1,210,0.000677
22,2020,36045,Jefferson,1183.0,16,7,7.7,40,4315,0.002066
23,2020,36047,Kings,21917.0,18,8,7.5,312,179878,0.002193
24,2020,36049,Lewis,295.0,14,7,8.0,18,1269,0.002119
25,2020,36051,Livingston,716.0,15,6,8.2,28,2095,0.001171
26,2020,36053,Madison,743.0,13,7,8.7,30,2708,0.001976
27,2020,36055,Monroe,7898.0,14,8,7.9,210,28214,0.002747
28,2020,36057,Montgomery,686.0,17,7,7.8,21,2462,0.000849
29,2020,36059,Nassau,10857.0,12,8,9.7,394,60098,0.003021
30,2020,36061,New York,11804.0,16,8,8.3,180,83332,0.008621
31,2020,36063,Niagara,3073.0,14,8,8.1,82,8640,0.001112
32,2020,36065,Oneida,3070.0,16,8,8.0,88,10140,0.001642
33,2020,36067,Onondaga,5156.0,14,8,8.1,152,18885,0.002532
34,2020,36069,Ontario,1322.0,13,7,8.5,58,3824,0.002155
35,2020,36071,Orange,3697.0,15,7,8.7,161,18227,0.002358
36,2020,36073,Orleans,570.0,16,7,8.0,20,1754,0.000542
37,2020,36075,Oswego,1612.0,15,7,8.0,81,5016,0.001357
38,2020,36077,Otsego,745.0,15,7,7.8,22,2245,0.001923
39,2020,36079,Putnam,918.0,12,8,9.3,32,4031,0.003401
40,2020,36081,Queens,17867.0,19,8,8.7,353,202448,0.001626
41,2020,36083,Rensselaer,1896.0,15,8,8.2,42,5856,0.001661
42,2020,36085,Richmond,4900.0,15,8,9.1,78,19801,0.002294
43,2020,36087,Rockland,2420.0,17,6,8.7,71,16379,0.002625
44,2020,36089,St. Lawrence,1373.0,18,7,7.6,47,5093,0.001961
45,2020,36091,Saratoga,2325.0,11,6,8.9,80,7118,0.001650
46,2020,36093,Schenectady,1827.0,15,8,8.2,39,6144,0.002232
47,2020,36095,Schoharie,397.0,15,7,8.1,38,1226,0.001319
48,2020,36097,Schuyler,268.0,15,6,8.3,10,747,0.001675
49,2020,36099,Seneca,472.0,15,6,8.2,23,1606,0.001808
51,2020,36103,Suffolk,14740.0,13,8,9.3,684,67541,0.002667
52,2020,36105,Sullivan,1109.0,17,8,8.3,55,3883,0.001894
53,2020,36107,Tioga,565.0,14,7,8.6,19,1843,0.001359
54,2020,36109,Tompkins,866.0,14,7,7.7,42,4160,0.003704
55,2020,36111,Ulster,2199.0,16,7,8.1,77,9437,0.003436
56,2020,36113,Warren,857.0,13,7,8.5,27,2628,0.003817
57,2020,36115,Washington,821.0,14,7,8.4,36,2629,0.001404
58,2020,36117,Wayne,1221.0,15,7,8.6,57,3530,0.001044
59,2020,36119,Westchester,7306.0,15,8,9.1,175,55634,0.003876
60,2020,36121,Wyoming,500.0,14,6,8.2,23,1366,0.002146
61,2020,36123,Yates,305.0,15,5,8.8,12,1587,0.001208

In [21]:
# Saving the new and cleaned dataset
file_path = "2022_clean_dataset.csv"
clean_data.to_csv(file_path, index=False)